[package]
name = "lua"
description = "Low-level lua bindings for rust"
version = "0.2.0"
edition = "2021"

[dependencies]
enum_num_match = { path = "../enum_num_match" }

[build-dependencies]
bindgen = "0.59.2"
pkg-config = "0.3.24"

[features]
luajit = []
